updates
- shellcheck
- update git-meta-diff to diff logs not diffs
- consolidate / cleanup completions

diff --git a/bin/cargo-open b/bin/cargo-open
--- a/bin/cargo-open
+++ b/bin/cargo-open
@@ -1,15 +1,29 @@
-#!/bin/bash -euf -o pipefail
+#!/bin/bash
 
-crate=$(cargo metadata | jq -r ".packages[] | select(.name == \"${@: -1}\") | .manifest_path")
+set -euf -o pipefail
+
+if [ $# -gt 1 ] && [[ "$1" == "open" ]]; then
+  shift
+fi
+
+if [ $# -ne 1 ] || [[ "${*:-1}" == "-h" ]] || [[ "${*:-1}" == "--help" ]]; then
+  echo "Usage: cargo open <crate>"
+  exit 1
+fi
+
+crate=$(cargo metadata --format-version=1 | jq -r "limit(1; .packages[] | select(.name == \"${*:-1}\") | .manifest_path)")
 
 if [[ -z "$crate" ]]; then
-  cargo metadata | jq -r ".packages[].name" | sort -u
+  echo "Usage: cargo open <crate>"
+  echo "Couldn't find crate \"${*:-1}\", valid crates:"
+  cargo metadata --format-version=1 | jq -r ".packages[].name" | sort -u
   exit 1
 fi
 
 if [[ -z "$EDITOR" ]]; then
+  # shellcheck disable=SC2016
   echo '$EDITOR is not set'
   exit 1
 fi
 
-exec $EDITOR $(dirname "$crate")
+exec "$EDITOR" "$(dirname "$crate")"
diff --git a/bin/git-fresh b/bin/git-fresh
--- a/bin/git-fresh
+++ b/bin/git-fresh
@@ -3,44 +3,44 @@
 set -eu -o pipefail
 
 usage() {
-    echo "Usage: $0 [<branch-to-rebase-on>]   (default branch=origin/master)"
-    exit
+    echo "Usage: git fresh [<branch-to-rebase-on>]   (default branch=origin/master)"
+    exit 1
 }
 
-if [ "$#" -eq 1 ]; then
+if [ $# -eq 1 ]; then
   if [[ "$1" == "-h" || "$1" == "--help" ]]; then
     usage
-  else
-    target="$1"
   fi
-elif [ "$#" -eq 0 ]; then
+  target=$1
+elif [ $# -eq 0 ]; then
   target=origin/master
 else
   usage
 fi
 
 if [[ "$target" == */* ]]; then
-  git fetch --prune ${target%%/*}
+  git fetch --prune "${target%%/*}"
 else
   git fetch --prune
 fi
 
 current=$(git rev-parse --abbrev-ref HEAD)
-for branch in $(echo "$GIT_PURGE_KEEP_BRANCHES"); do
-  if echo "$current" | egrep -q "$branch"; then
-    echo "Skipping rebase of $current since it is blacklisted in GIT_PURGE_KEEP_BRANCHES=$GIT_PURGE_KEEP_BRANCHES"
-    exit 1
-  fi
-done
+purge_keep_branches=(${GIT_PURGE_KEEP_BRANCHES:-})
+keep_branches="$(printf "|%s" "${purge_keep_branches[@]}")"
+# #| removes the leading |
+if grep -qE "${keep_branches#|}" <<< "$current" ; then
+  echo "Skipping rebase of $current since it is blacklisted in GIT_PURGE_KEEP_BRANCHES=$GIT_PURGE_KEEP_BRANCHES"
+  exit 1
+fi
 
-if ! git diff --quiet $(git merge-base HEAD ${target})..${target}; then
+if ! git diff --quiet "$(git merge-base HEAD "${target}")..${target}"; then
   if ! git diff --quiet; then
     stashed=1
     git stash
   fi
-  git rebase ${target}
+  git rebase "${target}"
   if [ -n "${stashed:-}" ]; then
     git stash pop
   fi
 fi
-git-purge-merged-branches ${target} || echo "Failed to delete some merged branches, continuing."
+git-purge-merged-branches "${target}" || echo "Failed to delete some merged branches, continuing."
