put everything in a function

diff --git a/bin/cargo-open b/bin/cargo-open
--- a/bin/cargo-open
+++ b/bin/cargo-open
@@ -2,31 +2,37 @@
 
 set -euf -o pipefail
 
-if [ $# -gt 1 ] && [[ "$1" == "open" ]]; then
-  shift
-fi
+main() {
+  local crate
 
-if [ $# -ne 1 ]; then
-  echo "Usage: cargo open <crate>"
-  exit 1
-elif [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
-  echo "Usage: cargo open <crate>"
-  exit
-fi
+  if [[ $# -gt 1 ]] && [[ "$1" == "open" ]]; then
+    shift
+  fi
 
-crate=$(cargo metadata --format-version=1 | jq -r "limit(1; .packages[] | select(.name == \"$1\") | .manifest_path)")
+  if [[ $# -ne 1 ]]; then
+    echo "Usage: cargo open <crate>"
+    exit 1
+  elif [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
+    echo "Usage: cargo open <crate>"
+    exit
+  fi
 
-if [[ -z "$crate" ]]; then
-  echo "Usage: cargo open <crate>"
-  echo "Couldn't find crate \"$1\", valid crates:"
-  cargo metadata --format-version=1 | jq -r ".packages[].name" | sort -u
-  exit 1
-fi
+  crate=$(cargo metadata --format-version=1 | jq -r "limit(1; .packages[] | select(.name == \"$1\") | .manifest_path)")
 
-if [[ -z "$EDITOR" ]]; then
-  # shellcheck disable=SC2016
-  echo '$EDITOR is not set'
-  exit 1
-fi
+  if [[ -z "$crate" ]]; then
+    echo "Usage: cargo open <crate>"
+    echo "Couldn't find crate \"$1\", valid crates:"
+    cargo metadata --format-version=1 | jq -r ".packages[].name" | sort -u
+    exit 1
+  fi
 
-exec "$EDITOR" "$(dirname "$crate")"
+  if [[ -z "$EDITOR" ]]; then
+    # shellcheck disable=SC2016
+    echo '$EDITOR is not set'
+    exit 1
+  fi
+
+  exec "$EDITOR" "$(dirname "$crate")"
+}
+
+main "$@"
diff --git a/bin/git-fresh b/bin/git-fresh
--- a/bin/git-fresh
+++ b/bin/git-fresh
@@ -6,48 +6,56 @@ usage() {
   echo "Usage: git fresh [<branch-to-rebase-on>]   (default branch=origin/master)"
 }
 
-if [ $# -eq 1 ]; then
-  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+main() {
+  local target current keep_branches stashed
+  local -a purge_keep_branches
+
+  if [[ $# -eq 1 ]]; then
+    if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+      usage
+      exit
+    fi
+    target=$1
+  elif [[ $# -eq 0 ]]; then
+    target=origin/master
+  else
     usage
-    exit
+    exit 1
   fi
-  target=$1
-elif [ $# -eq 0 ]; then
-  target=origin/master
-else
-  usage
-  exit 1
-fi
 
-if [[ "$target" == */* ]]; then
-  git fetch --prune "${target%%/*}"
-else
-  git fetch --prune
-fi
-
-current=$(git rev-parse --abbrev-ref --verify HEAD)
-purge_keep_branches=(${GIT_PURGE_KEEP_BRANCHES:-})
-keep_branches="$(printf "|%s" "${purge_keep_branches[@]}")"
-# #| removes the leading |
-if grep -qE "${keep_branches#|}" <<< "$current" ; then
-  echo "Skipping rebase of $current since it is blacklisted in GIT_PURGE_KEEP_BRANCHES=$GIT_PURGE_KEEP_BRANCHES" 1>&2
-  if ! (git pull || git config "branch.$current.merge"); then
-    echo "Setting upstream branch: git branch --set-upstream-to=origin/$current" 1>&2
-    git branch --set-upstream-to="origin/$current"
-    git pull
+  if [[ "$target" == */* ]]; then
+    git fetch --prune "${target%%/*}"
+  else
+    git fetch --prune
   fi
-  git-purge-merged-branches "${current}" || echo "Failed to delete some merged branches, continuing."
-else
-  if ! git diff --quiet --ignore-submodules=dirty "$(git merge-base HEAD "${target}")..${target}"; then
-    if ! git diff --quiet --ignore-submodules=dirty; then
-      stashed=1
-      git stash
+
+  current=$(git rev-parse --abbrev-ref --verify HEAD)
+  purge_keep_branches=(master ${GIT_PURGE_KEEP_BRANCHES:-})
+  keep_branches="$(printf "|%s" "${purge_keep_branches[@]}")"
+
+  # #| removes the leading "|"
+  if grep -qiE "${keep_branches#|}" <<< "$current" ; then
+    echo "Skipping rebase of $current since it is blacklisted in GIT_PURGE_KEEP_BRANCHES=$GIT_PURGE_KEEP_BRANCHES" 1>&2
+    if ! (git pull || git config "branch.$current.merge"); then
+      echo "Setting upstream branch: git branch --set-upstream-to=origin/$current" 1>&2
+      git branch --set-upstream-to="origin/$current"
+      git pull
     fi
-    git rebase "${target}"
-    if [ -n "${stashed:-}" ]; then
-      git stash pop
+    git-purge-merged-branches "${current}" || echo "Failed to delete some merged branches, continuing."
+  else
+    if ! git diff --quiet --ignore-submodules=dirty "$(git merge-base HEAD "${target}")..${target}"; then
+      if ! git diff --quiet --ignore-submodules=dirty; then
+        stashed=1
+        git stash
+      fi
+      git rebase "${target}"
+      if [[ -n "${stashed:-}" ]]; then
+        git stash pop
+      fi
     fi
-  fi
 
-  git-purge-merged-branches "${target}" || echo "Failed to delete some merged branches, continuing."
-fi
+    git-purge-merged-branches "${target}" || echo "Failed to delete some merged branches, continuing."
+  fi
+}
+
+main "$@"
