don't git-pr master

diff --git a/bin/git-pr b/bin/git-pr
--- a/bin/git-pr
+++ b/bin/git-pr
@@ -46,6 +46,11 @@ main() {
     shift
   done
 
+  if [[ "$branch" == "master" ]]; then
+    echo "ERROR! You're on master!"
+    exit 1
+  fi
+
   if [[ "$fresh" == "1" ]]; then
     git fresh
   fi
